# Generated by Django 4.0.4 on 2022-05-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travelapp', '0002_customer_name_staff_name_tour_name_tourguide_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gender',
            field=models.CharField(default='', max_length=20),
        ),
    ]
